### ISSUE TITLE
webshag  give an error on start up

### ISSUE THREAD

**Issue by hamzabitu** [wereallfeds/webshag#1]
root@Hunter:~# python webshag_gui.py
Traceback (most recent call last):
  File "webshag_gui.py", line 25, in <module>
    gui.run()
  File "/root/webshag/webshag/gui/gui.py", line 72, in run
    app = WebshagGUI(redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/root/webshag/webshag/gui/gui.py", line 85, in OnInit
    window = WebshagWindow(None, -1, WEBSHAG + ' ' + WEBSHAG_VERSION)
  File "/root/webshag/webshag/gui/gui.py", line 161, in __init__
    self.__infoPanel = gui_info.Panel(self.__notebook, self)
  File "/root/webshag/webshag/gui/gui_info.py", line 103, in __init__
    rootSizer.AddGrowableCol(1)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 15364, in AddGrowableCol
    return _core_.FlexGridSizer_AddGrowableCol(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!m_cols || idx < (size_t)m_cols" failed at ../src/common/sizer.cpp(1980) in AddGrowableCol(): invalid column index

**Comment by ghost** [comment]
I'm experiencing the same issue. Were you able to resolve it?

**Comment by oyeLucky1024** [comment]
I fixed it by commenting out couple of lines for AddGrowableCol where it is passed twice with 2 parameters of 0 and 1

basically there are two lines for .AddGrowableCol with parameters 0 and 1.
I commented out couple of  lines in code for gui module where parameter is 1 and it webshag gui works fine for me.
(I will toggle to comment out all 0 parameters and see if there is any change in gui and will update if something interesting is found..) 

you will need to comment out .AddGrowableCol(1)  in couple of places  in gui module

in your install directory go to

> webshag->webshag->gui

 and comment out this line in following files at code lines (or just search for it in atom by opening the code)

**gui_info.py:**

comment out line number 103
rootSizer.AddGrowableCol(1)

**gui_pscan.py:**

comment out line number 105
rootSizer.AddGrowableCol(1)

**gui_uscan.py:**

comment out line 104
settingsSizerGrid.AddGrowableCol(1)

**gui_fuzz.py:**

comment out line 105
checksSizerGrid.AddGrowableCol(1)

comment out line 111
settingsSizerGrid.AddGrowableCol(1)
